<?php

use Illuminate\Database\Seeder;

class AvatarsMediaSeeder extends Seeder {

  public function run() {
    $media = array(
        array('id' => '1','file' => NULL,'model_type' => 'App\\User','model_id' => '3','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar1','file_name' => 'avatar1.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '178469','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:11:30','updated_at' => '2020-05-26 11:11:32'),
        array('id' => '2','file' => NULL,'model_type' => 'App\\User','model_id' => '4','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar2','file_name' => 'avatar2.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '160968','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:11:39','updated_at' => '2020-05-26 11:11:39'),
        array('id' => '3','file' => NULL,'model_type' => 'App\\User','model_id' => '5','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar3','file_name' => 'avatar3.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '154600','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:12:06','updated_at' => '2020-05-26 11:12:06'),
        array('id' => '4','file' => NULL,'model_type' => 'App\\User','model_id' => '6','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar4','file_name' => 'avatar4.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '165650','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:12:12','updated_at' => '2020-05-26 11:12:13'),
        array('id' => '5','file' => NULL,'model_type' => 'App\\User','model_id' => '7','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar5','file_name' => 'avatar5.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '175722','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:12:18','updated_at' => '2020-05-26 11:12:18'),
        array('id' => '6','file' => NULL,'model_type' => 'App\\User','model_id' => '8','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar6','file_name' => 'avatar6.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '158571','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:12:58','updated_at' => '2020-05-26 11:12:59'),
        array('id' => '7','file' => NULL,'model_type' => 'App\\User','model_id' => '9','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar7','file_name' => 'avatar7.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '200324','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:09','updated_at' => '2020-05-26 11:13:09'),
        array('id' => '8','file' => NULL,'model_type' => 'App\\User','model_id' => '10','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar8','file_name' => 'avatar8.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '27184','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:17','updated_at' => '2020-05-26 11:13:18'),
        array('id' => '9','file' => NULL,'model_type' => 'App\\User','model_id' => '11','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar9','file_name' => 'avatar9.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '19406','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:23','updated_at' => '2020-05-26 11:13:23'),
        array('id' => '10','file' => NULL,'model_type' => 'App\\User','model_id' => '12','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar10','file_name' => 'avatar10.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '24651','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:29','updated_at' => '2020-05-26 11:13:29'),
        array('id' => '11','file' => NULL,'model_type' => 'App\\User','model_id' => '13','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar11','file_name' => 'avatar11.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '26439','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:17','updated_at' => '2020-05-26 11:15:17'),
        array('id' => '12','file' => NULL,'model_type' => 'App\\User','model_id' => '14','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar12','file_name' => 'avatar12.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '17201','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:23','updated_at' => '2020-05-26 11:15:23'),
        array('id' => '13','file' => NULL,'model_type' => 'App\\User','model_id' => '15','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar13','file_name' => 'avatar13.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '31426','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:28','updated_at' => '2020-05-26 11:15:28'),
        array('id' => '14','file' => NULL,'model_type' => 'App\\User','model_id' => '16','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar14','file_name' => 'avatar14.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '19361','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:33','updated_at' => '2020-05-26 11:15:33'),
        array('id' => '15','file' => NULL,'model_type' => 'App\\User','model_id' => '17','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar15','file_name' => 'avatar15.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '24455','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:39','updated_at' => '2020-05-26 11:15:39'),
        array('id' => '16','file' => NULL,'model_type' => 'App\\User','model_id' => '18','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar16','file_name' => 'avatar16.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '20843','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:44','updated_at' => '2020-05-26 11:15:45'),
        array('id' => '17','file' => NULL,'model_type' => 'App\\User','model_id' => '19','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar17','file_name' => 'avatar17.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '16568','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:50','updated_at' => '2020-05-26 11:15:50'),
        array('id' => '18','file' => NULL,'model_type' => 'App\\User','model_id' => '20','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar18','file_name' => 'avatar18.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '21848','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:54','updated_at' => '2020-05-26 11:15:54'),
        array('id' => '19','file' => NULL,'model_type' => 'App\\User','model_id' => '21','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar19','file_name' => 'avatar19.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '31065','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:16:01','updated_at' => '2020-05-26 11:16:01'),
        array('id' => '20','file' => NULL,'model_type' => 'App\\User','model_id' => '22','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar20','file_name' => 'avatar20.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '178469','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:23:46','updated_at' => '2020-05-26 11:23:47'),
        array('id' => '21','file' => NULL,'model_type' => 'App\\User','model_id' => '23','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar21','file_name' => 'avatar21.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '160968','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:23:52','updated_at' => '2020-05-26 11:23:53'),
        array('id' => '22','file' => NULL,'model_type' => 'App\\User','model_id' => '24','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar22','file_name' => 'avatar22.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '154600','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:23:59','updated_at' => '2020-05-26 11:23:59'),
        array('id' => '23','file' => NULL,'model_type' => 'App\\User','model_id' => '25','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar23','file_name' => 'avatar23.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '165650','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:03','updated_at' => '2020-05-26 11:24:04'),
        array('id' => '24','file' => NULL,'model_type' => 'App\\User','model_id' => '26','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar24','file_name' => 'avatar24.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '26439','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:08','updated_at' => '2020-05-26 11:24:08'),
        array('id' => '25','file' => NULL,'model_type' => 'App\\User','model_id' => '27','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar25','file_name' => 'avatar25.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '17201','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:12','updated_at' => '2020-05-26 11:24:12'),
        array('id' => '26','file' => NULL,'model_type' => 'App\\User','model_id' => '28','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar26','file_name' => 'avatar26.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '31426','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:21','updated_at' => '2020-05-26 11:24:21'),
        array('id' => '27','file' => NULL,'model_type' => 'App\\User','model_id' => '29','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar27','file_name' => 'avatar27.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '19361','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:25:08','updated_at' => '2020-05-26 11:25:08'),
        array('id' => '28','file' => NULL,'model_type' => 'App\\User','model_id' => '30','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar28','file_name' => 'avatar28.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '158571','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:27:42','updated_at' => '2020-05-26 11:27:42'),
        array('id' => '29','file' => NULL,'model_type' => 'App\\User','model_id' => '31','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar29','file_name' => 'avatar29.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '200324','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:27:48','updated_at' => '2020-05-26 11:27:48'),
        array('id' => '30','file' => NULL,'model_type' => 'App\\User','model_id' => '32','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatar','name' => 'avatar30','file_name' => 'avatar30.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '175722','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:27:59','updated_at' => '2020-05-26 11:27:59')
    );

    DB::table('media')->insert($media);

  }
}
