<?php

use Illuminate\Database\Seeder;

class AvatarsMediaSeeder extends Seeder {

  public function run() {
    $media = array(
        array('id' => '1', 'model_type' => 'App\\User', 'model_id' => '3', 'collection_name' => 'avatar', 'name' => 'avatar1', 'file_name' => 'avatar1.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '178469', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:16:02', 'updated_at' => '2020-05-21 17:16:03'),
        array('id' => '2', 'model_type' => 'App\\User', 'model_id' => '4', 'collection_name' => 'avatar', 'name' => 'avatar2', 'file_name' => 'avatar2.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '160968', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:16:12', 'updated_at' => '2020-05-21 17:16:12'),
        array('id' => '3', 'model_type' => 'App\\User', 'model_id' => '5', 'collection_name' => 'avatar', 'name' => 'avatar3', 'file_name' => 'avatar3.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '154600', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:16:24', 'updated_at' => '2020-05-21 17:16:25'),
        array('id' => '4', 'model_type' => 'App\\User', 'model_id' => '6', 'collection_name' => 'avatar', 'name' => 'avatar4', 'file_name' => 'avatar4.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '165650', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:16:36', 'updated_at' => '2020-05-21 17:16:37'),
        array('id' => '5', 'model_type' => 'App\\User', 'model_id' => '7', 'collection_name' => 'avatar', 'name' => 'avatar6', 'file_name' => 'avatar6.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '158571', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:16:48', 'updated_at' => '2020-05-21 17:16:48'),
        array('id' => '6', 'model_type' => 'App\\User', 'model_id' => '9', 'collection_name' => 'avatar', 'name' => 'avatar10', 'file_name' => 'avatar10.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '24651', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:03', 'updated_at' => '2020-05-21 17:17:03'),
        array('id' => '7', 'model_type' => 'App\\User', 'model_id' => '10', 'collection_name' => 'avatar', 'name' => 'avatar11', 'file_name' => 'avatar11.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '26439', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:09', 'updated_at' => '2020-05-21 17:17:09'),
        array('id' => '8', 'model_type' => 'App\\User', 'model_id' => '11', 'collection_name' => 'avatar', 'name' => 'avatar12', 'file_name' => 'avatar12.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '17201', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:17', 'updated_at' => '2020-05-21 17:17:17'),
        array('id' => '9', 'model_type' => 'App\\User', 'model_id' => '12', 'collection_name' => 'avatar', 'name' => 'avatar13', 'file_name' => 'avatar13.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '31426', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:24', 'updated_at' => '2020-05-21 17:17:24'),
        array('id' => '10', 'model_type' => 'App\\User', 'model_id' => '13', 'collection_name' => 'avatar', 'name' => 'avatar14', 'file_name' => 'avatar14.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '19361', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:29', 'updated_at' => '2020-05-21 17:17:29'),
        array('id' => '11', 'model_type' => 'App\\User', 'model_id' => '14', 'collection_name' => 'avatar', 'name' => 'avatar15', 'file_name' => 'avatar15.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '24455', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:34', 'updated_at' => '2020-05-21 17:17:34'),
        array('id' => '12', 'model_type' => 'App\\User', 'model_id' => '15', 'collection_name' => 'avatar', 'name' => 'avatar16', 'file_name' => 'avatar16.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '20843', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:17:39', 'updated_at' => '2020-05-21 17:17:39'),
        array('id' => '13', 'model_type' => 'App\\User', 'model_id' => '8', 'collection_name' => 'avatar', 'name' => 'avatar7', 'file_name' => 'avatar7.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '200324', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:18:24', 'updated_at' => '2020-05-21 17:18:24'),
        array('id' => '14', 'model_type' => 'App\\User', 'model_id' => '17', 'collection_name' => 'avatar', 'name' => 'avatar17', 'file_name' => 'avatar17.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '16568', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:19:30', 'updated_at' => '2020-05-21 17:19:31'),
        array('id' => '15', 'model_type' => 'App\\User', 'model_id' => '18', 'collection_name' => 'avatar', 'name' => 'avatar18', 'file_name' => 'avatar18.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '21848', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:19:35', 'updated_at' => '2020-05-21 17:19:35'),
        array('id' => '16', 'model_type' => 'App\\User', 'model_id' => '19', 'collection_name' => 'avatar', 'name' => 'avatar19', 'file_name' => 'avatar19.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '31065', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:19:39', 'updated_at' => '2020-05-21 17:19:39'),
        array('id' => '17', 'model_type' => 'App\\User', 'model_id' => '31', 'collection_name' => 'avatar', 'name' => 'avatar7', 'file_name' => 'avatar7.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '200324', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:20:21', 'updated_at' => '2020-05-21 17:20:22'),
        array('id' => '18', 'model_type' => 'App\\User', 'model_id' => '32', 'collection_name' => 'avatar', 'name' => 'avatar5', 'file_name' => 'avatar5.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '175722', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:20:26', 'updated_at' => '2020-05-21 17:20:26'),
        array('id' => '19', 'model_type' => 'App\\User', 'model_id' => '16', 'collection_name' => 'avatar', 'name' => 'avatar5', 'file_name' => 'avatar5.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '175722', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:22:26', 'updated_at' => '2020-05-21 17:22:26'),
        array('id' => '20', 'model_type' => 'App\\User', 'model_id' => '20', 'collection_name' => 'avatar', 'name' => 'avatar2', 'file_name' => 'avatar2.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '160968', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:22:58', 'updated_at' => '2020-05-21 17:22:59'),
        array('id' => '21', 'model_type' => 'App\\User', 'model_id' => '21', 'collection_name' => 'avatar', 'name' => 'avatar4', 'file_name' => 'avatar4.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '165650', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:08', 'updated_at' => '2020-05-21 17:23:09'),
        array('id' => '22', 'model_type' => 'App\\User', 'model_id' => '22', 'collection_name' => 'avatar', 'name' => 'avatar9', 'file_name' => 'avatar9.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '19406', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:17', 'updated_at' => '2020-05-21 17:23:17'),
        array('id' => '23', 'model_type' => 'App\\User', 'model_id' => '23', 'collection_name' => 'avatar', 'name' => 'avatar13', 'file_name' => 'avatar13.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '31426', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:26', 'updated_at' => '2020-05-21 17:23:26'),
        array('id' => '24', 'model_type' => 'App\\User', 'model_id' => '24', 'collection_name' => 'avatar', 'name' => 'avatar14', 'file_name' => 'avatar14.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '19361', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:34', 'updated_at' => '2020-05-21 17:23:35'),
        array('id' => '25', 'model_type' => 'App\\User', 'model_id' => '25', 'collection_name' => 'avatar', 'name' => 'avatar17', 'file_name' => 'avatar17.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '16568', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:43', 'updated_at' => '2020-05-21 17:23:43'),
        array('id' => '26', 'model_type' => 'App\\User', 'model_id' => '26', 'collection_name' => 'avatar', 'name' => 'avatar8', 'file_name' => 'avatar8.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '27184', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:49', 'updated_at' => '2020-05-21 17:23:50'),
        array('id' => '27', 'model_type' => 'App\\User', 'model_id' => '27', 'collection_name' => 'avatar', 'name' => 'avatar16', 'file_name' => 'avatar16.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '20843', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:23:56', 'updated_at' => '2020-05-21 17:23:56'),
        array('id' => '28', 'model_type' => 'App\\User', 'model_id' => '28', 'collection_name' => 'avatar', 'name' => 'avatar10', 'file_name' => 'avatar10.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '24651', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:24:04', 'updated_at' => '2020-05-21 17:24:04'),
        array('id' => '29', 'model_type' => 'App\\User', 'model_id' => '29', 'collection_name' => 'avatar', 'name' => 'avatar6', 'file_name' => 'avatar6.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '158571', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:24:09', 'updated_at' => '2020-05-21 17:24:09'),
        array('id' => '30', 'model_type' => 'App\\User', 'model_id' => '30', 'collection_name' => 'avatar', 'name' => 'avatar1', 'file_name' => 'avatar1.jpg', 'mime_type' => 'image/jpeg', 'disk' => 'mediaFiles', 'size' => '178469', 'manipulations' => '[]', 'custom_properties' => '{"generated_conversions": {"thumb": true}}', 'responsive_images' => '[]', 'order_column' => '1', 'created_at' => '2020-05-21 17:24:14', 'updated_at' => '2020-05-21 17:24:15')
    );

    DB::table('media')->insert($media);

  }
}
