<?php

use Illuminate\Database\Seeder;

class MediaSeeder extends Seeder {

  public function run() {
    $media = array(
        array('id' => '1','file' => NULL,'model_type' => 'App\\User','model_id' => '3','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar1','file_name' => 'avatar1.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '178469','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:11:30','updated_at' => '2020-05-26 11:11:32'),
        array('id' => '3','file' => NULL,'model_type' => 'App\\User','model_id' => '5','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar3','file_name' => 'avatar3.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '154600','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:12:06','updated_at' => '2020-05-26 11:12:06'),
        array('id' => '6','file' => NULL,'model_type' => 'App\\User','model_id' => '8','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar6','file_name' => 'avatar6.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '158571','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:12:58','updated_at' => '2020-05-26 11:12:59'),
        array('id' => '7','file' => NULL,'model_type' => 'App\\User','model_id' => '9','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar7','file_name' => 'avatar7.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '200324','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:09','updated_at' => '2020-05-26 11:13:09'),
        array('id' => '8','file' => NULL,'model_type' => 'App\\User','model_id' => '10','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar8','file_name' => 'avatar8.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '27184','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:17','updated_at' => '2020-05-26 11:13:18'),
        array('id' => '9','file' => NULL,'model_type' => 'App\\User','model_id' => '11','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar9','file_name' => 'avatar9.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '19406','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:23','updated_at' => '2020-05-26 11:13:23'),
        array('id' => '10','file' => NULL,'model_type' => 'App\\User','model_id' => '12','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar10','file_name' => 'avatar10.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '24651','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:13:29','updated_at' => '2020-05-26 11:13:29'),
        array('id' => '11','file' => NULL,'model_type' => 'App\\User','model_id' => '13','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar11','file_name' => 'avatar11.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '26439','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:17','updated_at' => '2020-05-26 11:15:17'),
        array('id' => '12','file' => NULL,'model_type' => 'App\\User','model_id' => '14','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar12','file_name' => 'avatar12.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '17201','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:23','updated_at' => '2020-05-26 11:15:23'),
        array('id' => '13','file' => NULL,'model_type' => 'App\\User','model_id' => '15','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar13','file_name' => 'avatar13.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '31426','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:28','updated_at' => '2020-05-26 11:15:28'),
        array('id' => '14','file' => NULL,'model_type' => 'App\\User','model_id' => '16','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar14','file_name' => 'avatar14.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '19361','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:33','updated_at' => '2020-05-26 11:15:33'),
        array('id' => '15','file' => NULL,'model_type' => 'App\\User','model_id' => '17','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar15','file_name' => 'avatar15.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '24455','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:39','updated_at' => '2020-05-26 11:15:39'),
        array('id' => '16','file' => NULL,'model_type' => 'App\\User','model_id' => '18','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar16','file_name' => 'avatar16.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '20843','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:44','updated_at' => '2020-05-26 11:15:45'),
        array('id' => '17','file' => NULL,'model_type' => 'App\\User','model_id' => '19','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar17','file_name' => 'avatar17.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '16568','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:50','updated_at' => '2020-05-26 11:15:50'),
        array('id' => '18','file' => NULL,'model_type' => 'App\\User','model_id' => '20','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar18','file_name' => 'avatar18.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '21848','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:15:54','updated_at' => '2020-05-26 11:15:54'),
        array('id' => '19','file' => NULL,'model_type' => 'App\\User','model_id' => '21','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar19','file_name' => 'avatar19.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '31065','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:16:01','updated_at' => '2020-05-26 11:16:01'),
        array('id' => '20','file' => NULL,'model_type' => 'App\\User','model_id' => '22','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar20','file_name' => 'avatar20.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '178469','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:23:46','updated_at' => '2020-05-26 11:23:47'),
        array('id' => '21','file' => NULL,'model_type' => 'App\\User','model_id' => '23','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar21','file_name' => 'avatar21.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '160968','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:23:52','updated_at' => '2020-05-26 11:23:53'),
        array('id' => '22','file' => NULL,'model_type' => 'App\\User','model_id' => '24','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar22','file_name' => 'avatar22.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '154600','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:23:59','updated_at' => '2020-05-26 11:23:59'),
        array('id' => '23','file' => NULL,'model_type' => 'App\\User','model_id' => '25','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar23','file_name' => 'avatar23.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '165650','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:03','updated_at' => '2020-05-26 11:24:04'),
        array('id' => '24','file' => NULL,'model_type' => 'App\\User','model_id' => '26','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar24','file_name' => 'avatar24.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '26439','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:08','updated_at' => '2020-05-26 11:24:08'),
        array('id' => '25','file' => NULL,'model_type' => 'App\\User','model_id' => '27','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar25','file_name' => 'avatar25.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '17201','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:12','updated_at' => '2020-05-26 11:24:12'),
        array('id' => '26','file' => NULL,'model_type' => 'App\\User','model_id' => '28','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar26','file_name' => 'avatar26.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '31426','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:24:21','updated_at' => '2020-05-26 11:24:21'),
        array('id' => '27','file' => NULL,'model_type' => 'App\\User','model_id' => '29','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar27','file_name' => 'avatar27.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '19361','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:25:08','updated_at' => '2020-05-26 11:25:08'),
        array('id' => '28','file' => NULL,'model_type' => 'App\\User','model_id' => '30','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar28','file_name' => 'avatar28.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '158571','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:27:42','updated_at' => '2020-05-26 11:27:42'),
        array('id' => '29','file' => NULL,'model_type' => 'App\\User','model_id' => '31','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar29','file_name' => 'avatar29.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '200324','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:27:48','updated_at' => '2020-05-26 11:27:48'),
        array('id' => '30','file' => NULL,'model_type' => 'App\\User','model_id' => '32','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar30','file_name' => 'avatar30.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '175722','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-26 11:27:59','updated_at' => '2020-05-26 11:27:59'),
        array('id' => '31','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '1','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner1','file_name' => 'partner1.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1691','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:42:33','updated_at' => '2020-05-27 14:42:33'),
        array('id' => '32','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '2','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner2','file_name' => 'partner2.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '2350','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:42:48','updated_at' => '2020-05-27 14:42:48'),
        array('id' => '33','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '3','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner3','file_name' => 'partner3.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '2023','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:42:54','updated_at' => '2020-05-27 14:42:55'),
        array('id' => '34','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '4','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner4','file_name' => 'partner4.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '2431','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:01','updated_at' => '2020-05-27 14:43:01'),
        array('id' => '35','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '5','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner5','file_name' => 'partner5.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '3054','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:10','updated_at' => '2020-05-27 14:43:11'),
        array('id' => '36','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '6','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner6','file_name' => 'partner6.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '3645','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:16','updated_at' => '2020-05-27 14:43:16'),
        array('id' => '37','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '7','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner7','file_name' => 'partner7.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1811','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:21','updated_at' => '2020-05-27 14:43:21'),
        array('id' => '38','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '8','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner8','file_name' => 'partner8.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '2745','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:26','updated_at' => '2020-05-27 14:43:26'),
        array('id' => '39','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '9','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner9','file_name' => 'partner9.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '2952','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:30','updated_at' => '2020-05-27 14:43:31'),
        array('id' => '40','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '10','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner10','file_name' => 'partner10.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1081','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:43:36','updated_at' => '2020-05-27 14:43:36'),
        array('id' => '41','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '11','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner11','file_name' => 'partner11.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1256','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:09','updated_at' => '2020-05-27 14:44:10'),
        array('id' => '42','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '12','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner12','file_name' => 'partner12.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1255','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:21','updated_at' => '2020-05-27 14:44:22'),
        array('id' => '43','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '13','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner13','file_name' => 'partner13.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1232','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:31','updated_at' => '2020-05-27 14:44:31'),
        array('id' => '44','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '14','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner14','file_name' => 'partner14.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1331','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:38','updated_at' => '2020-05-27 14:44:38'),
        array('id' => '45','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '15','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner15','file_name' => 'partner15.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '2422','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:46','updated_at' => '2020-05-27 14:44:46'),
        array('id' => '46','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '16','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner16','file_name' => 'partner16.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1030','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:51','updated_at' => '2020-05-27 14:44:51'),
        array('id' => '47','file' => NULL,'model_type' => 'App\\Models\\Partner','model_id' => '17','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'partners','name' => 'partner17','file_name' => 'partner17.png','mime_type' => 'image/png','disk' => 'mediaFiles','size' => '1100','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-05-27 14:44:55','updated_at' => '2020-05-27 14:44:56'),
        array('id' => '48','file' => NULL,'model_type' => 'App\\Models\\Sponsor','model_id' => '1','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar1','file_name' => 'avatar1.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '154600','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-06-01 11:14:48','updated_at' => '2020-06-01 11:14:49'),
        array('id' => '49','file' => NULL,'model_type' => 'App\\Models\\Sponsor','model_id' => '2','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'avatars','name' => 'avatar2','file_name' => 'avatar2.jpg','mime_type' => 'image/jpeg','disk' => 'mediaFiles','size' => '160968','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"thumb": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-06-01 11:15:06','updated_at' => '2020-06-01 11:15:06'),
        array('id' => '50','file' => NULL,'model_type' => 'App\\Models\\Category','model_id' => '4','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'image','name' => 'partner3','file_name' => 'partner3.png','mime_type' => 'image/png','disk' => 'public','size' => '2023','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"image": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-08-04 00:50:54','updated_at' => '2020-08-04 00:50:54'),
        array('id' => '51','file' => NULL,'model_type' => 'App\\Models\\Category','model_id' => '3','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'image','name' => 'partner4','file_name' => 'partner4.png','mime_type' => 'image/png','disk' => 'public','size' => '2431','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"image": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-08-04 00:51:09','updated_at' => '2020-08-04 00:51:09'),
        array('id' => '52','file' => NULL,'model_type' => 'App\\Models\\Category','model_id' => '2','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'image','name' => 'partner5','file_name' => 'partner5.png','mime_type' => 'image/png','disk' => 'public','size' => '3054','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"image": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-08-04 00:51:24','updated_at' => '2020-08-04 00:51:25'),
        array('id' => '53','file' => NULL,'model_type' => 'App\\Models\\Category','model_id' => '1','mime' => NULL,'hash' => NULL,'width' => NULL,'height' => NULL,'collection_name' => 'image','name' => 'partner6','file_name' => 'partner6.png','mime_type' => 'image/png','disk' => 'public','size' => '3645','manipulations' => '[]','custom_properties' => '{"generated_conversions": {"image": true}}','responsive_images' => '[]','order_column' => '1','created_at' => '2020-08-04 00:51:38','updated_at' => '2020-08-04 00:51:38')
    );

    DB::table('media')->insert($media);

  }
}
