<?php

use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder {

  public function run() {
    $data = array();
    $data [] = ["name" => "Afghanistan", "iso"=>"af", "code"=>"93", "style"=>"-1px -3180px"];
    $data [] = ["name" => "Albania", "iso"=>"al", "code"=>"355", "style"=>"-1px -1310px"];
    $data [] = ["name" => "Algeria", "iso"=>"dz", "code"=>"213", "style"=>"-1px -681px"];
    $data [] = ["name" => "American Samoa", "iso"=>"as", "code"=>"1", "style"=>"-1px -2058px"];
    $data [] = ["name" => "Andorra", "iso"=>"ad", "code"=>"376", "style"=>"-1px -766px"];
    $data [] = ["name" => "Angola", "iso"=>"ao", "code"=>"244", "style"=>"-1px -2636px"];
    $data [] = ["name" => "Anguilla", "iso"=>"ai", "code"=>"1", "style"=>"-1px -2687px"];
    $data [] = ["name" => "Antigua &amp; Barbuda", "iso"=>"ag", "code"=>"1", "style"=>"-1px -1140px"];
    $data [] = ["name" => "Argentina", "iso"=>"ar", "code"=>"54", "style"=>"-1px -3282px"];
    $data [] = ["name" => "Armenia", "iso"=>"am", "code"=>"374", "style"=>"-1px -205px"];
    $data [] = ["name" => "Aruba", "iso"=>"aw", "code"=>"297", "style"=>"-1px -1021px"];
    $data [] = ["name" => "Ascension Island", "iso"=>"ac", "code"=>"247", "style"=>"-1px -86px"];
    $data [] = ["name" => "Australia", "iso"=>"au", "code"=>"61", "style"=>"-1px -2279px"];
    $data [] = ["name" => "Austria", "iso"=>"at", "code"=>"43", "style"=>"-1px -1735px"];
    $data [] = ["name" => "Azerbaijan", "iso"=>"az", "code"=>"994", "style"=>"-1px -1599px"];
    $data [] = ["name" => "Bahamas ", "iso"=>"bs", "code"=>"1", "style"=>"-1px -460px"];
    $data [] = ["name" => "Bahrain", "iso"=>"bh", "code"=>"973", "style"=>"-1px -1956px"];
    $data [] = ["name" => "Bangladesh", "iso"=>"bd", "code"=>"880", "style"=>"-1px -2364px"];
    $data [] = ["name" => "Barbados", "iso"=>"bb", "code"=>"1", "style"=>"-1px -2075px"];
    $data [] = ["name" => "Belarus", "iso"=>"by", "code"=>"375", "style"=>"-1px -1412px"];
    $data [] = ["name" => "Belgium", "iso"=>"be", "code"=>"32", "style"=>"-1px -1px"];
    $data [] = ["name" => "Belize", "iso"=>"bz", "code"=>"501", "style"=>"-1px -613px"];
    $data [] = ["name" => "Benin", "iso"=>"bj", "code"=>"229", "style"=>"-1px -1684px"];
    $data [] = ["name" => "Bermuda", "iso"=>"bm", "code"=>"1", "style"=>"-1px -2585px"];
    $data [] = ["name" => "Bhutan", "iso"=>"bt", "code"=>"975", "style"=>"-1px -2483px"];
    $data [] = ["name" => "Bolivia", "iso"=>"bo", "code"=>"591", "style"=>"-1px -2177px"];
    $data [] = ["name" => "Bosnia &amp; Herzegovina", "iso"=>"ba", "code"=>"387", "style"=>"-1px -2092px"];
    $data [] = ["name" => "Botswana", "iso"=>"bw", "code"=>"267", "style"=>"-1px -3724px"];
    $data [] = ["name" => "Brazil", "iso"=>"br", "code"=>"55", "style"=>"-1px -1004px"];
    $data [] = ["name" => "British Indian Ocean", "iso"=>"io", "code"=>"246", "style"=>"-1px -86px"];
    $data [] = ["name" => "British Virgin Islands", "iso"=>"vg", "code"=>"1", "style"=>"-1px -1854px"];
    $data [] = ["name" => "Brunei", "iso"=>"bn", "code"=>"673", "style"=>"-1px -2228px"];
    $data [] = ["name" => "Bulgaria", "iso"=>"bg", "code"=>"359", "style"=>"-1px -3537px"];
    $data [] = ["name" => "Burkina Faso", "iso"=>"bf", "code"=>"226", "style"=>"-1px -953px"];
    $data [] = ["name" => "Burundi", "iso"=>"bi", "code"=>"257", "style"=>"-1px -2551px"];
    $data [] = ["name" => "Cambodia", "iso"=>"kh", "code"=>"855", "style"=>"-1px -290px"];
    $data [] = ["name" => "Cameroon", "iso"=>"cm", "code"=>"237", "style"=>"-1px -2806px"];
    $data [] = ["name" => "Canada", "iso"=>"ca", "code"=>"1", "style"=>"-1px -1803px"];
    $data [] = ["name" => "Cape Verde", "iso"=>"cv", "code"=>"238", "style"=>"-1px -3639px"];
    $data [] = ["name" => "Caribbean Netherlands", "iso"=>"bq", "code"=>"599", "style"=>"-1px -3741px"];
    $data [] = ["name" => "Cayman Islands", "iso"=>"ky", "code"=>"1", "style"=>"-1px -375px"];
    $data [] = ["name" => "Central African Republic", "iso"=>"cf", "code"=>"236", "style"=>"-1px -2466px"];
    $data [] = ["name" => "Chad", "iso"=>"td", "code"=>"235", "style"=>"-1px -1055px"];
    $data [] = ["name" => "Chile", "iso"=>"cl", "code"=>"56", "style"=>"-1px -1752px"];
    $data [] = ["name" => "China", "iso"=>"cn", "code"=>"86", "style"=>"-1px -1072px"];
    $data [] = ["name" => "Colombia", "iso"=>"co", "code"=>"57", "style"=>"-1px -409px"];
    $data [] = ["name" => "Comoros", "iso"=>"km", "code"=>"269", "style"=>"-1px -1871px"];
    $data [] = ["name" => "Congo - Brazzaville", "iso"=>"cg", "code"=>"242", "style"=>"-1px -2398px"];
    $data [] = ["name" => "Congo - Kinshasa", "iso"=>"cd", "code"=>"243", "style"=>"-1px -1990px"];
    $data [] = ["name" => "Cook Islands", "iso"=>"ck", "code"=>"682", "style"=>"-1px -3112px"];
    $data [] = ["name" => "Costa Rica", "iso"=>"cr", "code"=>"506", "style"=>"-1px -2857px"];
    $data [] = ["name" => "Côte d’Ivoire", "iso"=>"ci", "code"=>"225", "style"=>"-1px -2194px"];
    $data [] = ["name" => "Croatia", "iso"=>"hr", "code"=>"385", "style"=>"-1px -1174px"];
    $data [] = ["name" => "Cuba", "iso"=>"cu", "code"=>"53", "style"=>"-1px -987px"];
    $data [] = ["name" => "Curaçao", "iso"=>"cw", "code"=>"599", "style"=>"-1px -3758px"];
    $data [] = ["name" => "Cyprus", "iso"=>"cy", "code"=>"357", "style"=>"-1px -732px"];
    $data [] = ["name" => "Czechia", "iso"=>"cz", "code"=>"420", "style"=>"-1px -3095px"];
    $data [] = ["name" => "Denmark", "iso"=>"dk", "code"=>"45", "style"=>"-1px -1820px"];
    $data [] = ["name" => "Djibouti", "iso"=>"dj", "code"=>"253", "style"=>"-1px -2874px"];
    $data [] = ["name" => "Dominica", "iso"=>"dm", "code"=>"1", "style"=>"-1px -3350px"];
    $data [] = ["name" => "Dominican Republic", "iso"=>"do", "code"=>"1", "style"=>"-1px -2007px"];
    $data [] = ["name" => "Ecuador", "iso"=>"ec", "code"=>"593", "style"=>"-1px -1531px"];
    $data [] = ["name" => "Egypt", "iso"=>"eg", "code"=>"20", "style"=>"-1px -3027px"];
    $data [] = ["name" => "El Salvador", "iso"=>"sv", "code"=>"503", "style"=>"-1px -2160px"];
    $data [] = ["name" => "Equatorial Guinea", "iso"=>"gq", "code"=>"240", "style"=>"-1px -1973px"];
    $data [] = ["name" => "Eritrea", "iso"=>"er", "code"=>"291", "style"=>"-1px -936px"];
    $data [] = ["name" => "Estonia", "iso"=>"ee", "code"=>"372", "style"=>"-1px -3333px"];
    $data [] = ["name" => "Eswatini", "iso"=>"sz", "code"=>"268", "style"=>"-1px -3129px"];
    $data [] = ["name" => "Ethiopia", "iso"=>"et", "code"=>"251", "style"=>"-1px -3367px"];
    $data [] = ["name" => "Falkland Islands (Islas Malvinas)", "iso"=>"fk", "code"=>"500", "style"=>"-1px -3809px"];
    $data [] = ["name" => "Faroe Islands", "iso"=>"fo", "code"=>"298", "style"=>"-1px -1429px"];
    $data [] = ["name" => "Fiji", "iso"=>"fj", "code"=>"679", "style"=>"-1px -2500px"];
    $data [] = ["name" => "Finland", "iso"=>"fi", "code"=>"358", "style"=>"-1px -2568px"];
    $data [] = ["name" => "France", "iso"=>"fr", "code"=>"33", "style"=>"-1px -324px"];
    $data [] = ["name" => "French Guiana", "iso"=>"gf", "code"=>"594", "style"=>"-1px -324px"];
    $data [] = ["name" => "French Polynesia", "iso"=>"pf", "code"=>"689", "style"=>"-1px -2262px"];
    $data [] = ["name" => "Gabon", "iso"=>"ga", "code"=>"241", "style"=>"-1px -1157px"];
    $data [] = ["name" => "Gambia", "iso"=>"gm", "code"=>"220", "style"=>"-1px -817px"];
    $data [] = ["name" => "Georgia", "iso"=>"ge", "code"=>"995", "style"=>"-1px -1123px"];
    $data [] = ["name" => "Germany", "iso"=>"de", "code"=>"49", "style"=>"-1px -3452px"];
    $data [] = ["name" => "Ghana", "iso"=>"gh", "code"=>"233", "style"=>"-1px -2891px"];
    $data [] = ["name" => "Gibraltar", "iso"=>"gi", "code"=>"350", "style"=>"-1px -341px"];
    $data [] = ["name" => "Greece", "iso"=>"gr", "code"=>"30", "style"=>"-1px -188px"];
    $data [] = ["name" => "Greenland", "iso"=>"gl", "code"=>"299", "style"=>"-1px -2347px"];
    $data [] = ["name" => "Grenada", "iso"=>"gd", "code"=>"1", "style"=>"-1px -3316px"];
    $data [] = ["name" => "Guadeloupe", "iso"=>"gp", "code"=>"590", "style"=>"-1px -511px"];
    $data [] = ["name" => "Guam", "iso"=>"gu", "code"=>"1", "style"=>"-1px -3265px"];
    $data [] = ["name" => "Guatemala", "iso"=>"gt", "code"=>"502", "style"=>"-1px -1208px"];
    $data [] = ["name" => "Guinea", "iso"=>"gn", "code"=>"224", "style"=>"-1px -3520px"];
    $data [] = ["name" => "Guinea-Bissau", "iso"=>"gw", "code"=>"245", "style"=>"-1px -2602px"];
    $data [] = ["name" => "Guyana", "iso"=>"gy", "code"=>"592", "style"=>"-1px -1038px"];
    $data [] = ["name" => "Haiti", "iso"=>"ht", "code"=>"509", "style"=>"-1px -392px"];
    $data [] = ["name" => "Honduras", "iso"=>"hn", "code"=>"504", "style"=>"-1px -2959px"];
    $data [] = ["name" => "Hong Kong", "iso"=>"hk", "code"=>"852", "style"=>"-1px -3707px"];
    $data [] = ["name" => "Hungary", "iso"=>"hu", "code"=>"36", "style"=>"-1px -902px"];
    $data [] = ["name" => "Iceland", "iso"=>"is", "code"=>"354", "style"=>"-1px -2704px"];
    $data [] = ["name" => "India", "iso"=>"in", "code"=>"91", "style"=>"-1px -2245px"];
    $data [] = ["name" => "Indonesia", "iso"=>"id", "code"=>"62", "style"=>"-1px -2653px"];
    $data [] = ["name" => "Iran", "iso"=>"ir", "code"=>"98", "style"=>"-1px -2738px"];
    $data [] = ["name" => "Iraq", "iso"=>"iq", "code"=>"964", "style"=>"-1px -851px"];
    $data [] = ["name" => "Ireland", "iso"=>"ie", "code"=>"353", "style"=>"-1px -2670px"];
    $data [] = ["name" => "Israel", "iso"=>"il", "code"=>"972", "style"=>"-1px -426px"];
    $data [] = ["name" => "Italy", "iso"=>"it", "code"=>"39", "style"=>"-1px -154px"];
    $data [] = ["name" => "Jamaica", "iso"=>"jm", "code"=>"1", "style"=>"-1px -2296px"];
    $data [] = ["name" => "Japan", "iso"=>"jp", "code"=>"81", "style"=>"-1px -528px"];
    $data [] = ["name" => "Jordan", "iso"=>"jo", "code"=>"962", "style"=>"-1px -1905px"];
    $data [] = ["name" => "Kazakhstan", "iso"=>"kz", "code"=>"7", "style"=>"-1px -1565px"];
    $data [] = ["name" => "Kenya", "iso"=>"ke", "code"=>"254", "style"=>"-1px -3605px"];
    $data [] = ["name" => "Kiribati", "iso"=>"ki", "code"=>"686", "style"=>"-1px -477px"];
    $data [] = ["name" => "Kosovo", "iso"=>"xk", "code"=>"383", "style"=>"-1px -3860px"];
    $data [] = ["name" => "Kuwait", "iso"=>"kw", "code"=>"965", "style"=>"-1px -3435px"];
    $data [] = ["name" => "Kyrgyzstan", "iso"=>"kg", "code"=>"996", "style"=>"-1px -2143px"];
    $data [] = ["name" => "Laos", "iso"=>"la", "code"=>"856", "style"=>"-1px -562px"];
    $data [] = ["name" => "Latvia", "iso"=>"lv", "code"=>"371", "style"=>"-1px -2619px"];
    $data [] = ["name" => "Lebanon", "iso"=>"lb", "code"=>"961", "style"=>"-1px -1616px"];
    $data [] = ["name" => "Lesotho", "iso"=>"ls", "code"=>"266", "style"=>"-1px -3010px"];
    $data [] = ["name" => "Liberia", "iso"=>"lr", "code"=>"231", "style"=>"-1px -2823px"];
    $data [] = ["name" => "Libya", "iso"=>"ly", "code"=>"218", "style"=>"-1px -137px"];
    $data [] = ["name" => "Liechtenstein", "iso"=>"li", "code"=>"423", "style"=>"-1px -1276px"];
    $data [] = ["name" => "Lithuania", "iso"=>"lt", "code"=>"370", "style"=>"-1px -1446px"];
    $data [] = ["name" => "Luxembourg", "iso"=>"lu", "code"=>"352", "style"=>"-1px -1922px"];
    $data [] = ["name" => "Macao", "iso"=>"mo", "code"=>"853", "style"=>"-1px -3554px"];
    $data [] = ["name" => "Madagascar", "iso"=>"mg", "code"=>"261", "style"=>"-1px -1667px"];
    $data [] = ["name" => "Malawi", "iso"=>"mw", "code"=>"265", "style"=>"-1px -2942px"];
    $data [] = ["name" => "Malaysia", "iso"=>"my", "code"=>"60", "style"=>"-1px -2517px"];
    $data [] = ["name" => "Maldives", "iso"=>"mv", "code"=>"960", "style"=>"-1px -800px"];
    $data [] = ["name" => "Mali", "iso"=>"ml", "code"=>"223", "style"=>"-1px -3469px"];
    $data [] = ["name" => "Malta", "iso"=>"mt", "code"=>"356", "style"=>"-1px -2041px"];
    $data [] = ["name" => "Marshall Islands", "iso"=>"mh", "code"=>"692", "style"=>"-1px -1463px"];
    $data [] = ["name" => "Martinique", "iso"=>"mq", "code"=>"596", "style"=>"-1px -239px"];
    $data [] = ["name" => "Mauritania", "iso"=>"mr", "code"=>"222", "style"=>"-1px -307px"];
    $data [] = ["name" => "Mauritius", "iso"=>"mu", "code"=>"230", "style"=>"-1px -2993px"];
    $data [] = ["name" => "Mexico", "iso"=>"mx", "code"=>"52", "style"=>"-1px -2755px"];
    $data [] = ["name" => "Micronesia", "iso"=>"fm", "code"=>"691", "style"=>"-1px -2313px"];
    $data [] = ["name" => "Moldova", "iso"=>"md", "code"=>"373", "style"=>"-1px -3690px"];
    $data [] = ["name" => "Monaco", "iso"=>"mc", "code"=>"377", "style"=>"-1px -1191px"];
    $data [] = ["name" => "Mongolia", "iso"=>"mn", "code"=>"976", "style"=>"-1px -3503px"];
    $data [] = ["name" => "Montenegro", "iso"=>"me", "code"=>"382", "style"=>"-1px -2976px"];
    $data [] = ["name" => "Montserrat", "iso"=>"ms", "code"=>"1", "style"=>"-1px -749px"];
    $data [] = ["name" => "Morocco", "iso"=>"ma", "code"=>"212", "style"=>"-1px -3214px"];
    $data [] = ["name" => "Mozambique", "iso"=>"mz", "code"=>"258", "style"=>"-1px -834px"];
    $data [] = ["name" => "Myanmar (Burma)", "iso"=>"mm", "code"=>"95", "style"=>"-1px -18px"];
    $data [] = ["name" => "Namibia", "iso"=>"na", "code"=>"264", "style"=>"-1px -2534px"];
    $data [] = ["name" => "Nauru", "iso"=>"nr", "code"=>"674", "style"=>"-1px -2330px"];
    $data [] = ["name" => "Nepal", "iso"=>"np", "code"=>"977", "style"=>"-1px -120px"];
    $data [] = ["name" => "Netherlands", "iso"=>"nl", "code"=>"31", "style"=>"-1px -1888px"];
    $data [] = ["name" => "New Caledonia", "iso"=>"nc", "code"=>"687", "style"=>"-1px -1650px"];
    $data [] = ["name" => "New Zealand", "iso"=>"nz", "code"=>"64", "style"=>"-1px -2024px"];
    $data [] = ["name" => "Nicaragua", "iso"=>"ni", "code"=>"505", "style"=>"-1px -171px"];
    $data [] = ["name" => "Niger", "iso"=>"ne", "code"=>"227", "style"=>"-1px -715px"];
    $data [] = ["name" => "Nigeria", "iso"=>"ng", "code"=>"234", "style"=>"-1px -3418px"];
    $data [] = ["name" => "Niue", "iso"=>"nu", "code"=>"683", "style"=>"-1px -2840px"];
    $data [] = ["name" => "Norfolk Island", "iso"=>"nf", "code"=>"672", "style"=>"-1px -256px"];
    $data [] = ["name" => "North Korea", "iso"=>"kp", "code"=>"850", "style"=>"-1px -2415px"];
    $data [] = ["name" => "North Macedonia", "iso"=>"mk", "code"=>"389", "style"=>"-1px -1769px"];
    $data [] = ["name" => "Northern Mariana Islands", "iso"=>"mp", "code"=>"1", "style"=>"-1px -919px"];
    $data [] = ["name" => "Norway", "iso"=>"no", "code"=>"47", "style"=>"-1px -1089px"];
    $data [] = ["name" => "Oman", "iso"=>"om", "code"=>"968", "style"=>"-1px -3384px"];
    $data [] = ["name" => "Pakistan", "iso"=>"pk", "code"=>"92", "style"=>"-1px -2772px"];
    $data [] = ["name" => "Palau", "iso"=>"pw", "code"=>"680", "style"=>"-1px -273px"];
    $data [] = ["name" => "Palestine", "iso"=>"ps", "code"=>"970", "style"=>"-1px -1548px"];
    $data [] = ["name" => "Panama", "iso"=>"pa", "code"=>"507", "style"=>"-1px -1106px"];
    $data [] = ["name" => "Papua New Guinea", "iso"=>"pg", "code"=>"675", "style"=>"-1px -1939px"];
    $data [] = ["name" => "Paraguay", "iso"=>"py", "code"=>"595", "style"=>"-1px -3231px"];
    $data [] = ["name" => "Peru", "iso"=>"pe", "code"=>"51", "style"=>"-1px -1225px"];
    $data [] = ["name" => "Philippines", "iso"=>"ph", "code"=>"63", "style"=>"-1px -2432px"];
    $data [] = ["name" => "Poland", "iso"=>"pl", "code"=>"48", "style"=>"-1px -1514px"];
    $data [] = ["name" => "Portugal", "iso"=>"pt", "code"=>"351", "style"=>"-1px -664px"];
    $data [] = ["name" => "Puerto Rico", "iso"=>"pr", "code"=>"1", "style"=>"-1px -596px"];
    $data [] = ["name" => "Qatar", "iso"=>"qa", "code"=>"974", "style"=>"-1px -579px"];
    $data [] = ["name" => "Réunion", "iso"=>"re", "code"=>"262", "style"=>"-1px -324px"];
    $data [] = ["name" => "Romania", "iso"=>"ro", "code"=>"40", "style"=>"-1px -885px"];
    $data [] = ["name" => "Russia", "iso"=>"ru", "code"=>"7", "style"=>"-1px -868px"];
    $data [] = ["name" => "Rwanda", "iso"=>"rw", "code"=>"250", "style"=>"-1px -3673px"];
    $data [] = ["name" => "Samoa", "iso"=>"ws", "code"=>"685", "style"=>"-1px -3163px"];
    $data [] = ["name" => "San Marino", "iso"=>"sm", "code"=>"378", "style"=>"-1px -2908px"];
    $data [] = ["name" => "São Tomé &amp; Príncipe", "iso"=>"st", "code"=>"239", "style"=>"-1px -3299px"];
    $data [] = ["name" => "Saudi Arabia", "iso"=>"sa", "code"=>"966", "style"=>"-1px -52px"];
    $data [] = ["name" => "Senegal", "iso"=>"sn", "code"=>"221", "style"=>"-1px -2925px"];
    $data [] = ["name" => "Serbia", "iso"=>"rs", "code"=>"381", "style"=>"-1px -3401px"];
    $data [] = ["name" => "Seychelles", "iso"=>"sc", "code"=>"248", "style"=>"-1px -1327px"];
    $data [] = ["name" => "Sierra Leone", "iso"=>"sl", "code"=>"232", "style"=>"-1px -970px"];
    $data [] = ["name" => "Singapore", "iso"=>"sg", "code"=>"65", "style"=>"-1px -35px"];
    $data [] = ["name" => "Sint Maarten", "iso"=>"sx", "code"=>"1", "style"=>"-1px -3826px"];
    $data [] = ["name" => "Slovakia", "iso"=>"sk", "code"=>"421", "style"=>"-1px -3044px"];
    $data [] = ["name" => "Slovenia", "iso"=>"si", "code"=>"386", "style"=>"-1px -1582px"];
    $data [] = ["name" => "Solomon Islands", "iso"=>"sb", "code"=>"677", "style"=>"-1px -1361px"];
    $data [] = ["name" => "Somalia", "iso"=>"so", "code"=>"252", "style"=>"-1px -1786px"];
    $data [] = ["name" => "South Africa", "iso"=>"za", "code"=>"27", "style"=>"-1px -3248px"];
    $data [] = ["name" => "South Korea", "iso"=>"kr", "code"=>"82", "style"=>"-1px -3078px"];
    $data [] = ["name" => "South Sudan", "iso"=>"ss", "code"=>"211", "style"=>"-1px -3775px"];
    $data [] = ["name" => "Spain", "iso"=>"es", "code"=>"34", "style"=>"-1px -1480px"];
    $data [] = ["name" => "Sri Lanka", "iso"=>"lk", "code"=>"94", "style"=>"-1px -3622px"];
    $data [] = ["name" => "St. Barthélemy", "iso"=>"bl", "code"=>"590", "style"=>"-1px -324px"];
    $data [] = ["name" => "St. Helena", "iso"=>"sh", "code"=>"290", "style"=>"-1px -630px"];
    $data [] = ["name" => "St. Kitts &amp; Nevis", "iso"=>"kn", "code"=>"1", "style"=>"-1px -103px"];
    $data [] = ["name" => "St. Lucia", "iso"=>"lc", "code"=>"1", "style"=>"-1px -1837px"];
    $data [] = ["name" => "St. Martin", "iso"=>"mf", "code"=>"590", "style"=>"-1px -86px"];
    $data [] = ["name" => "St. Pierre &amp; Miquelon", "iso"=>"pm", "code"=>"508", "style"=>"-1px -1378px"];
    $data [] = ["name" => "St. Vincent &amp; Grenadines", "iso"=>"vc", "code"=>"1", "style"=>"-1px -3588px"];
    $data [] = ["name" => "Sudan", "iso"=>"sd", "code"=>"249", "style"=>"-1px -443px"];
    $data [] = ["name" => "Suriname", "iso"=>"sr", "code"=>"597", "style"=>"-1px -3656px"];
    $data [] = ["name" => "Sweden", "iso"=>"se", "code"=>"46", "style"=>"-1px -494px"];
    $data [] = ["name" => "Switzerland", "iso"=>"ch", "code"=>"41", "style"=>"-1px -1718px"];
    $data [] = ["name" => "Syria", "iso"=>"sy", "code"=>"963", "style"=>"-1px -2449px"];
    $data [] = ["name" => "Taiwan", "iso"=>"tw", "code"=>"886", "style"=>"-1px -647px"];
    $data [] = ["name" => "Tajikistan", "iso"=>"tj", "code"=>"992", "style"=>"-1px -222px"];
    $data [] = ["name" => "Tanzania", "iso"=>"tz", "code"=>"255", "style"=>"-1px -3146px"];
    $data [] = ["name" => "Thailand", "iso"=>"th", "code"=>"66", "style"=>"-1px -1242px"];
    $data [] = ["name" => "Timor-Leste", "iso"=>"tl", "code"=>"670", "style"=>"-1px -3843px"];
    $data [] = ["name" => "Togo", "iso"=>"tg", "code"=>"228", "style"=>"-1px -783px"];
    $data [] = ["name" => "Tokelau", "iso"=>"tk", "code"=>"690", "style"=>"-1px -3792px"];
    $data [] = ["name" => "Tonga", "iso"=>"to", "code"=>"676", "style"=>"-1px -1395px"];
    $data [] = ["name" => "Trinidad &amp; Tobago", "iso"=>"tt", "code"=>"1", "style"=>"-1px -545px"];
    $data [] = ["name" => "Tunisia", "iso"=>"tn", "code"=>"216", "style"=>"-1px -698px"];
    $data [] = ["name" => "Turkey", "iso"=>"tr", "code"=>"90", "style"=>"-1px -2126px"];
    $data [] = ["name" => "Turkmenistan", "iso"=>"tm", "code"=>"993", "style"=>"-1px -3486px"];
    $data [] = ["name" => "Turks &amp; Caicos Islands", "iso"=>"tc", "code"=>"1", "style"=>"-1px -1701px"];
    $data [] = ["name" => "Tuvalu", "iso"=>"tv", "code"=>"688", "style"=>"-1px -358px"];
    $data [] = ["name" => "U.S. Virgin Islands", "iso"=>"vi", "code"=>"1", "style"=>"-1px -2381px"];
    $data [] = ["name" => "Uganda", "iso"=>"ug", "code"=>"256", "style"=>"-1px -1497px"];
    $data [] = ["name" => "Ukraine", "iso"=>"ua", "code"=>"380", "style"=>"-1px -2721px"];
    $data [] = ["name" => "United Arab Emirates", "iso"=>"ae", "code"=>"971", "style"=>"-1px -3061px"];
    $data [] = ["name" => "United Kingdom", "iso"=>"gb", "code"=>"44", "style"=>"-1px -86px"];
    $data [] = ["name" => "United States", "iso"=>"us", "code"=>"1", "style"=>"-1px -69px"];
    $data [] = ["name" => "Uruguay", "iso"=>"uy", "code"=>"598", "style"=>"-1px -3571px"];
    $data [] = ["name" => "Uzbekistan", "iso"=>"uz", "code"=>"998", "style"=>"-1px -1293px"];
    $data [] = ["name" => "Vanuatu", "iso"=>"vu", "code"=>"678", "style"=>"-1px -1633px"];
    $data [] = ["name" => "Vatican City", "iso"=>"va", "code"=>"39", "style"=>"-1px -3197px"];
    $data [] = ["name" => "Venezuela", "iso"=>"ve", "code"=>"58", "style"=>"-1px -1344px"];
    $data [] = ["name" => "Vietnam", "iso"=>"vn", "code"=>"84", "style"=>"-1px -1259px"];
    $data [] = ["name" => "Wallis &amp; Futuna", "iso"=>"wf", "code"=>"681", "style"=>"-1px -324px"];
    $data [] = ["name" => "Yemen", "iso"=>"ye", "code"=>"967", "style"=>"-1px -2211px"];
    $data [] = ["name" => "Zambia", "iso"=>"zm", "code"=>"260", "style"=>"-1px -2109px"];
    $data [] = ["name" => "Zimbabwe", "iso"=>"zw ", "code"=>"263", "style"=>"-1px -2789px"];



    DB::table('regions')->insert($data);
  }
}
