<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Event extends Model implements HasMedia {

  protected $casts = ['date' => 'datetime', 'program' => "array"];
  protected $fillable = ["status"];

  use HasMediaTrait;

  public function users() {
    return $this->belongsToMany(User::class);
  }

  protected function performUpdate(Builder $query) {
      $events = self::get();
      foreach ($events as $key => $val) {
        $val->active = 0;
        $val->update();
      }
      return parent::performUpdate($query); // TODO: Change the autogenerated stub
  }

  public function registerMediaConversions(Media $media = null) {
    $this->addMediaConversion('thumb')
        ->width(130)
        ->height(130);
  }

  public static function activeEvent() {
    return Event::where('active', true)->first();
  }

  public function registerMediaCollections() {
    $this->addMediaCollection('banners')->useDisk('mediaFiles');
  }


}
